import type { VisualizationDefinition } from "@/simulations";

export const visualizations = [
  {
    id: "horizontal-scaling",
    lessonId: "01-02-horizontal-vs-vertical-scaling",
    kind: "horizontal-scaling",
    title: "Scaling and saturation lab",
    description: "Compare scale-up and scale-out while observing warm-up, queues, shared bottlenecks, and node failure.",
  },
  {
    id: "consistent-hash-ring",
    lessonId: "04-10-consistent-hashing",
    kind: "consistent-hashing",
    title: "Consistent hash-ring explorer",
    description: "Compare modulo and ring placement while changing membership, virtual nodes, failures, and migration policy.",
  },
  {
    id: "tail-latency",
    lessonId: "01-04-percentiles-tail-latency",
    kind: "tail-latency",
    title: "Tail-latency explorer",
    description: "See how percentiles, fan-out, queueing, and mitigations change user-visible latency and resource cost.",
  },
  {
    id: "cap",
    lessonId: "01-09-cap",
    kind: "cap",
    title: "CAP partition lab",
    description: "Partition replicas, issue reads and writes, and compare consistency, availability, conflict, and repair choices.",
  },
  {
    id: "load-balancing-algorithms",
    lessonId: "03-02-load-balancing-algorithms",
    kind: "load-balancing",
    title: "Load-balancing algorithm lab",
    description: "Replay one workload across routing policies while exposing work skew, queueing, hot keys, health, and remapping.",
  },
  {
    id: "transaction-isolation",
    lessonId: "04-05-transaction-isolation",
    kind: "transaction-isolation",
    title: "Transaction-isolation lab",
    description: "Step through concurrent schedules to expose anomalies, snapshots, conflicts, and invariant protection.",
  },
  {
    id: "cache-stampede",
    lessonId: "05-07-cache-stampede",
    kind: "cache-stampede",
    title: "Cache-stampede control room",
    description: "Trigger synchronized misses and compare coalescing, locks, jitter, refresh, and bounded stale responses.",
  },
  {
    id: "backpressure",
    lessonId: "06-09-backpressure",
    kind: "backpressure",
    title: "Backpressure pipeline lab",
    description: "Change producer, broker, consumer, and downstream capacity to observe backlog, loss, retries, and feedback.",
  },
  { id: "retry-jitter", lessonId: "08-03-exponential-backoff-and-jitter", kind: "scenario-lab", title: "Retry and jitter recovery lab", description: "Compare synchronized retry waves with deterministic, bounded jitter while a dependency recovers." },
  { id: "token-bucket", lessonId: "11-01-rate-limiter", kind: "scenario-lab", title: "Token-bucket admission lab", description: "Observe refill, burst allowance, sustained admission, rejection, and degraded limiter behavior." },
  { id: "circuit-breaker", lessonId: "08-05-circuit-breaker", kind: "scenario-lab", title: "Circuit-breaker recovery lab", description: "Trip a scoped circuit, fail fast, and probe recovery without flooding the dependency." },
  { id: "read-write-quorums", lessonId: "04-11-read-write-quorums", kind: "scenario-lab", title: "Read/write quorum lab", description: "Compare weak and overlapping replica sets while keeping protocol assumptions explicit." },
  { id: "replication", lessonId: "04-08-replication", kind: "scenario-lab", title: "Replication and failover timeline", description: "Follow log positions, stale reads, fencing, and promotion across a leader and followers." },
  { id: "partitioning-sharding", lessonId: "04-09-partitioning-and-sharding", kind: "scenario-lab", title: "Partitioning and shard-movement lab", description: "Expose hot-shard skew and a verified copy, catch-up, and cutover sequence." },
  { id: "message-queue-fundamentals", lessonId: "06-02-message-queue-fundamentals", kind: "scenario-lab", title: "Message-queue flow lab", description: "Trace durable publish, claim, side effects, acknowledgment, and bounded backlog." },
  { id: "delivery-semantics", lessonId: "06-06-delivery-semantics", kind: "scenario-lab", title: "Delivery semantics crash lab", description: "Crash a worker around its side effect and compare redelivery with idempotent handling." },
  { id: "consensus-raft", lessonId: "07-03-consensus-and-raft-intuition", kind: "scenario-lab", title: "Consensus and Raft intuition lab", description: "Elect a leader, replicate a log entry, and expose majority commit semantics." },
  { id: "distributed-locks", lessonId: "07-04-distributed-locks", kind: "scenario-lab", title: "Distributed lock and fencing lab", description: "Compare a lease alone with resource-enforced monotonic fencing tokens." },
  { id: "request-lifecycle", lessonId: "02-01-request-lifecycle", kind: "scenario-lab", title: "Request lifecycle budget lab", description: "Trace resolution, connection, routing, queueing, application work, and data access under one deadline." },
  { id: "dns", lessonId: "02-02-dns", kind: "scenario-lab", title: "DNS resolution and migration lab", description: "Follow recursive lookup, TTL caching, record changes, and stale endpoint behavior." },
  { id: "health-checks-failover", lessonId: "03-04-health-checks-and-failover", kind: "scenario-lab", title: "Health checks and failover lab", description: "Compare readiness hysteresis with detection, fencing, promotion, and routing convergence." },
  { id: "database-indexes", lessonId: "04-06-database-indexes", kind: "scenario-lab", title: "Database index access-path lab", description: "Compare scans and composite index seeks while exposing page reads and write cost." },
  { id: "btree-lsm", lessonId: "04-07-b-tree-vs-lsm", kind: "scenario-lab", title: "B-tree and LSM storage lab", description: "Move work between foreground reads, writes, flushes, and compaction." },
  { id: "cache-invalidation", lessonId: "05-06-cache-invalidation", kind: "scenario-lab", title: "Cache invalidation race lab", description: "Observe stale repopulation and version-aware commit-then-invalidate behavior." },
  { id: "hot-keys", lessonId: "05-08-hot-keys", kind: "scenario-lab", title: "Hot-key distribution lab", description: "Expose concentrated key ownership and compare replicas with request coalescing." },
  { id: "partitions-consumer-groups", lessonId: "06-04-partitions-and-consumer-groups", kind: "scenario-lab", title: "Partition and consumer-group lab", description: "Observe partition-limited parallelism, lag, revocation, offset handoff, and reassignment." },
  { id: "dead-letter-queues", lessonId: "06-08-dead-letter-queues", kind: "scenario-lab", title: "Dead-letter queue recovery lab", description: "Quarantine poison messages and perform a bounded, idempotent redrive." },
  { id: "distributed-tracing", lessonId: "09-02-distributed-tracing", kind: "scenario-lab", title: "Distributed tracing critical-path lab", description: "Propagate trace context, identify critical spans, and compare tail-based sampling." },
] satisfies VisualizationDefinition[];
